# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(blank=True, max_length=10)),
                ('album_logo', models.ImageField(blank=True, upload_to='music/album/logo')),
                ('album_artist', models.CharField(blank=True, max_length=70)),
                ('album_genre', models.CharField(blank=True, max_length=70)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('dislikes', models.IntegerField(blank=True, default=0)),
                ('published_date', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.IntegerField(blank=True, default=0)),
                ('album_id', models.IntegerField(blank=True, default=0)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='music/song/comment_img')),
                ('file', models.FileField(blank=True, upload_to='music/song/comment_file')),
                ('datetime', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.IntegerField(blank=True, default=0)),
                ('album_id', models.IntegerField(blank=True, default=0)),
                ('likes', models.BooleanField()),
                ('dislikes', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('created_date', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(blank=True, max_length=100)),
                ('song_genre', models.CharField(blank=True, max_length=70)),
                ('song_artist', models.CharField(blank=True, max_length=70)),
                ('date', models.DateField(blank=True)),
                ('song_file', models.FileField(blank=True, upload_to='music/song/file')),
                ('lyrics_file', models.FileField(blank=True, upload_to='music/song/lyrics')),
                ('lyrics', models.CharField(blank=True, max_length=2500)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('dislikes', models.IntegerField(blank=True, default=0)),
                ('downloads', models.IntegerField(blank=True, default=0)),
                ('album_id', models.IntegerField(blank=True, default=0)),
                ('playlist_id', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
