# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_auto_20190205_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
