# Generated by Django 2.1.7 on 2019-03-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_auto_20190215_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='dislikes',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='likes',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_favourite',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
