# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=50)),
                ('profile_photo', models.ImageField(blank=True, upload_to='image/profile')),
                ('cover_photo', models.ImageField(blank=True, upload_to='image/cover')),
                ('temporary_address', models.CharField(blank=True, max_length=50)),
                ('permanent_address', models.CharField(blank=True, max_length=50)),
                ('place_lived', models.CharField(blank=True, max_length=400)),
                ('birth_date', models.DateField(blank=True)),
                ('sex', models.CharField(blank=True, max_length=50)),
                ('about_you', models.CharField(blank=True, max_length=500)),
                ('skill', models.CharField(blank=True, max_length=500)),
                ('education_degree', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('language_known', models.CharField(blank=True, max_length=200)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('interested_in', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
