# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 08:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAdministration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.CharField(blank=True, max_length=500)),
                ('received', models.CharField(blank=True, max_length=500)),
                ('sent_pic', models.ImageField(blank=True, upload_to='img/msg/sent')),
                ('received_pic', models.ImageField(blank=True, upload_to='img/msg/recieved')),
                ('sent_file', models.FileField(blank=True, upload_to='file/msg/sent')),
                ('received_file', models.FileField(blank=True, upload_to='file/msg/recieved')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAdministration.Message'),
        ),
    ]
