# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdministration', '0005_auto_20190205_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
