# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdministration', '0008_usertracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertracker',
            old_name='last_login',
            new_name='last_seen',
        ),
    ]
