# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAdministration', '0009_auto_20190206_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, upload_to='image/userphotos')),
                ('cover_photo', models.ImageField(blank=True, upload_to='image/userphotos')),
                ('image', models.ImageField(blank=True, upload_to='image/userphotos')),
                ('file', models.FileField(blank=True, upload_to='image/userfiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
