# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdministration', '0011_auto_20190210_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertracker',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
