# Generated by Django 2.1.7 on 2019-03-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdministration', '0012_usertracker_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='follow_perm',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='friend',
            name='follower_perm',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='usertracker',
            name='active_status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
